---
# Basic setup for a React native workspace with expo support
# Documentation can be found here: https://www.gitpod.io/docs/references/gitpod-yml
image:
  file: .gitpod.dockerfile

# Configure git
gitConfig:
  core.autocrlf: "false"

# Define tasks that should be executed
# Documentation: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Install React native demo
    init: |
      chmod +x ./.devEnv/gitpod/scripts/install_react_native_demo.sh &&
      ./.devEnv/gitpod/scripts/install_react_native_demo.sh
    command: yarn start